-- FUNCION DE RECARGO %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

CREATE FUNCTION F_RECARGO ( @RECARGO DECIMAL(3,2) )
RETURNS @TABLA TABLE
(ID_PRODUCTO SMALLINT,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(50),
PRECIO MONEY,
RECARGO DECIMAL(3,2),
PRECIO_RECARGO MONEY,
TIPO_PRODUCTO SMALLINT,
MARCA SMALLINT,
STOC INT)
AS
BEGIN
	INSERT @TABLA
	SELECT ID_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO,
	@RECARGO, (PRECIO + (PRECIO * (1+ @RECARGO))), TP.TIPO, M.MARCA, STOCK FROM PRODUCTOS P, TIPOS_PRODUCTOS TP,
	MARCAS M WHERE P.ID_T_PRODUCTO = TP.ID_T_PRODUCTO AND P.ID_MARCA = M.ID_MARCA
	RETURN
END;
GO

-- FUNCION DE DESCUENTO %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

CREATE FUNCTION F_DESCUENTO ( @IMPORTE DECIMAL(10,2) , @DESCUENTO INT )
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @RESULTADO DECIMAL(10,2)
    
    SELECT @RESULTADO = @IMPORTE * (@DESCUENTO/100)
    
    RETURN @RESULTADO
END;
GO
