--/////////////// CARGA DE EMPLEADOS /////////////////

CREATE PROCEDURE SP_INSERT_EMPLEADO
@LEGAJO INT OUTPUT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@PUESTO INT,
@SEDE INT,
@TELEFONO BIGINT,
@FECHAINGRESO DATE
AS
BEGIN
	INSERT INTO EMPLEADOS(NOMBRE,APELLIDO,ID_PUESTO,ID_SEDE,TELEFONO,FECHA_INGRESO)
	VALUES (@NOMBRE,@APELLIDO,@PUESTO,@SEDE,@TELEFONO,@FECHAINGRESO);

	SET @LEGAJO = SCOPE_IDENTITY();
END;

-- SP PARA CARGAR LOS COMBO BOX COMPLEMENTARIOS

CREATE PROCEDURE SP_GET_PUESTOS
AS
BEGIN
	SELECT ID_PUESTO, PUESTO
	FROM PUESTOS
	ORDER BY PUESTO
END;

CREATE PROCEDURE SP_GET_SEDES
AS
BEGIN
	SELECT ID_SEDE, NOMBRE 
	FROM SEDES
	ORDER BY NOMBRE
END;


--//////////////// SP CARGA DE CLIENTE ///////////////////

CREATE PROCEDURE SP_INSERT_CLIENTE
@ID_CLIENTE INT OUTPUT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@ID_BARRIO INT,
@TELEFONO INT,
@EMAIL VARCHAR(100)
AS
BEGIN
	INSERT INTO CLIENTES (NOMBRE,APELLIDO,ID_BARRIO,TELEFONO,EMAIL)
	VALUES (@NOMBRE,@APELLIDO,@ID_BARRIO,@TELEFONO,@EMAIL);

	SET @ID_CLIENTE = SCOPE_IDENTITY();
END;

-- SP BARRIOS COMPLEMENTARIO

CREATE PROCEDURE SP_GET_BARRIOS
AS
BEGIN
	SELECT ID_BARRIO, BARRIO 
	FROM BARRIOS
	ORDER BY BARRIO
END;

--//////////////// SP CARGA DE PROVEEDORES ///////////////////

CREATE PROCEDURE SP_INSERT_PROVEEDORES
@ID_PROVEEDOR INT OUTPUT,
@NOMBRE VARCHAR(50),
@RAZON INT,
@CALLE VARCHAR(50),
@BARRIO INT
AS
BEGIN
	INSERT INTO PROVEEDORES (NOMBRE,ID_RAZON,CALLE,ID_BARRIO)
	VALUES (@NOMBRE,@RAZON,@CALLE,@BARRIO);

	SET @ID_PROVEEDOR = SCOPE_IDENTITY();
END;

-- SP RAZON SOCIAL COMPLEMENTARIO

CREATE PROCEDURE SP_GET_RAZON
AS
BEGIN
	SELECT ID_RAZON, DESCRIPCION 
	FROM RAZON_SOCIAL
	ORDER BY DESCRIPCION
END;

--//////////////// SP CARGA DE LUTHIER ///////////////////

CREATE PROCEDURE SP_INSERT_LUTHIERS
@ID_LUTHIER INT OUTPUT,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50)
AS
BEGIN
	INSERT INTO LUTHIERS (NOMBRE,APELLIDO)
	VALUES (@NOMBRE, @APELLIDO);

	SET @ID_LUTHIER = SCOPE_IDENTITY();
END;
