-- SP empleado cliente tipo de pago sede y envio

CREATE PROCEDURE SP_GET_EMPLEADO_X_SEDE
@SEDE INT
AS
BEGIN
	SELECT LEGAJO, NOMBRE, APELLIDO
	FROM EMPLEADOS
	WHERE ID_SEDE = @SEDE
	ORDER BY APELLIDO
END;

CREATE PROCEDURE SP_GET_CLIENTE
AS
BEGIN
	SELECT ID_CLIENTE, NOMBRE, APELLIDO 
	FROM CLIENTES
	ORDER BY APELLIDO
END;

CREATE PROCEDURE SP_GET_FORMA_PAGO
AS
BEGIN
	SELECT ID_PAGO, PAGO 
	FROM FORMA_PAGO
	ORDER BY PAGO
END;

CREATE PROCEDURE SP_GET_FORMA_ENVIO
AS
BEGIN
	SELECT ID_ENVIO, ENVIO 
	FROM FORMA_ENVIO
	ORDER BY ENVIO
END;


CREATE PROCEDURE SP_GET_LUTHIERS
AS 
BEGIN
	SELECT ID_LUTHIER, NOMBRE, APELLIDO
	FROM LUTHIERS
	ORDER BY APELLIDO
END 

CREATE PROCEDURE SP_GET_TIPO_SERVICIOS
AS 
BEGIN
	SELECT ID_T_SERV, SERVICIO 
	FROM TIPO_SERVICIO
	ORDER BY SERVICIO
END;

-- SP INSERTS DETALLE DE SERVICIO,  DETALLE DE FACTURA ///////////////////

CREATE PROCEDURE SP_INSERT_DET_SERVICIO
@FACTURA INT,
@LUTHIER INT,
@SERVICIO INT,
@PRECIO DECIMAL(10,2),
@HORAS INT
AS
BEGIN
	INSERT INTO DETALLE_SERVICIO (ID_DET_SERV, NRO_FACTURA, ID_LUTHIER, ID_T_SERV, PRECIO_X_HORA, HORAS)
	VALUES ((SELECT MAX(ID_DET_SERV) + 1 FROM DETALLE_SERVICIO),@FACTURA,@LUTHIER,@SERVICIO,@PRECIO,@HORAS)
END;

CREATE PROCEDURE SP_INSERT_FACTURAS
@legajo INT,
@cliente INT,
@pago INT,
@sede INT,
@envio INT,
@factura INT OUTPUT
AS
BEGIN

SELECT @factura = (max(NRO_FACTURA) +1) FROM FACTURAS

INSERT INTO FACTURAS(NRO_FACTURA, FECHA,LEGAJO, ID_CLIENTE,ID_PAGO, ID_SEDE, ID_ENVIO)
VALUES(@factura, GETDATE(), @legajo, @cliente,@pago, @sede, @envio)

END;

CREATE PROCEDURE SP_INSERT_DET_FACTURA
@FACTURA INT,
@PRODUCTO INT,
@CANTIDAD INT,
@PRECIO DECIMAL(10,2)
AS
BEGIN
	INSERT INTO DETALLE_FACTURA(ID_DET_FACT, NRO_FACTURA, ID_PRODUCTO, CANTIDAD,PRECIO)
	VALUES ((SELECT MAX(ID_DET_FACT) + 1 FROM DETALLE_FACTURA),@FACTURA,@PRODUCTO,@CANTIDAD,@PRECIO)
END;