-- ///////////////////////// PROCEDIMIENTOS DE CARGA DE PANTALLAS DE STOCK /////////////////////////////////

--PRODUCTOS

CREATE PROCEDURE SP_SCREEN_PRODUCTOS
AS
BEGIN
	SELECT P.ID_PRODUCTO 'ID_PRODUCTO', P.NOMBRE 'NOMBRE', T.TIPO 'TIPO', M.MARCA 'MARCA', V.NOMBRE 'PROVEEDOR',
	PA.PAIS 'PAIS', P.STOCK 'STOCK', P.PRECIO 'PRECIO'
	FROM PRODUCTOS P
	JOIN TIPOS_PRODUCTOS T ON T.ID_T_PRODUCTO = P.ID_T_PRODUCTO
	JOIN MARCAS M ON M.ID_MARCA = P.ID_MARCA
	JOIN PROVEEDORES V ON V.ID_PROVEEDOR = P.ID_PROVEEDOR
	JOIN PAISES PA ON PA.ID_PAIS = P.ID_PAIS
END;

--CLIENTES

CREATE PROCEDURE SP_SCREEN_CLIENTES
AS
BEGIN
	SELECT C.ID_CLIENTE 'ID', C.APELLIDO 'APELLIDO', C.NOMBRE 'NOMBRE', B.BARRIO 'BARRIO', C.TELEFONO 'TELEFONO', C.EMAIL 'EMAIL'
	FROM CLIENTES C
	JOIN BARRIOS B ON B.ID_BARRIO = C.ID_BARRIO
	ORDER BY C.APELLIDO
END;

--EMPLEADOS

CREATE PROCEDURE SP_SCREEN_EMPLEADOS
AS
BEGIN
	SELECT E.LEGAJO 'LEGAJO', S.NOMBRE 'SEDE', P.PUESTO 'PUESTO',E.APELLIDO 'APELLIDO', 
	E.NOMBRE 'NOMBRE', E.TELEFONO 'TELEFONO', E.FECHA_INGRESO 'INGRESO' 
	FROM EMPLEADOS E
	JOIN SEDES S ON S.ID_SEDE = E.ID_SEDE
	JOIN PUESTOS P ON P.ID_PUESTO = E.ID_PUESTO
	ORDER BY S.NOMBRE, P.PUESTO,  E.APELLIDO
END;


--PROVEEDORES

CREATE PROCEDURE SP_SCREEN_PROVEEDORES
AS
BEGIN
	SELECT P.ID_PROVEEDOR 'ID', P.NOMBRE 'PROVEEDOR', 
	R.DESCRIPCION 'RAZON', P.CALLE 'CALLE', B.BARRIO 'BARRIO'
	FROM PROVEEDORES P
	JOIN RAZON_SOCIAL R ON R.ID_RAZON = P.ID_RAZON
	JOIN BARRIOS B ON B.ID_BARRIO = P.ID_BARRIO
	ORDER BY P.NOMBRE
END;